# Generated by Django 5.2.7 on 2025-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackmodel',
            name='stack_name',
            field=models.CharField(max_length=100),
        ),
    ]
