# Generated by Django 5.2.7 on 2025-10-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authormodel',
            old_name='surname',
            new_name='surename',
        ),
    ]
