# Generated by Django 5.2.7 on 2025-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_surname_authormodel_surename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='surename',
            field=models.CharField(max_length=100),
        ),
    ]
