# Generated by Django 5.2.7 on 2025-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('photo', models.ImageField(upload_to='project_photos/')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[(0, 'Working'), (1, 'Sold'), (2, 'Starting'), (3, 'MVP'), (4, 'Completed')])),
                ('started_date', models.DateTimeField(null=True)),
                ('ended_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
