# Generated by Django 5.2.7 on 2025-10-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('project', '0002_alter_projectmodel_ended_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='link',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_photos', to='photos.photomodel'),
        ),
    ]
