# Generated by Django 5.2.7 on 2025-10-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectmodel_link_alter_projectmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='status',
            field=models.CharField(choices=[(5, 'Working'), (1, 'Sold'), (2, 'Starting'), (3, 'MVP'), (4, 'Completed')]),
        ),
    ]
