# Generated by Django 5.2.7 on 2025-10-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Working'), (1, 'Sold'), (2, 'Starting'), (3, 'MVP'), (4, 'Completed')], default=2),
        ),
    ]
