# Generated by Django 5.2.7 on 2025-10-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_projectmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='ended_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
