# Generated by Django 5.2.7 on 2025-10-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('project', '0006_alter_projectmodel_ended_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.authormodel'),
        ),
    ]
