# Generated by Django 5.2.7 on 2025-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_rename_surname_authormodel_surename'),
        ('project', '0007_projectmodel_author'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tag.tagmodel'),
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='author',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='authors.authormodel'),
        ),
    ]
