# Generated by Django 5.2.7 on 2025-10-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_projectmodel_tags_remove_projectmodel_author_and_more'),
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='stacks',
            field=models.ManyToManyField(blank=True, null=True, to='stack.stackmodel'),
        ),
    ]
