# Generated by Django 5.2.7 on 2025-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_projectmodel_stacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
