# Generated by Django 5.2.7 on 2025-10-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photomodel_project'),
        ('project', '0010_alter_projectmodel_link_alter_projectmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_photos', to='photos.photomodel'),
        ),
    ]
