# Generated by Django 5.2.7 on 2025-10-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photomodel_project'),
        ('project', '0011_alter_projectmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project_photos', to='photos.photomodel'),
        ),
    ]
