# Generated by Django 5.2.7 on 2025-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photomodel_project'),
        ('project', '0012_alter_projectmodel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='photo',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, related_name='Project_photos', to='photos.photomodel'),
        ),
    ]
