# Generated by Django 5.2.7 on 2025-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_authormodel_name_alter_authormodel_surename'),
        ('photos', '0002_remove_photomodel_project'),
        ('project', '0013_remove_projectmodel_photo_projectmodel_photo'),
        ('stack', '0002_alter_stackmodel_stack_name'),
        ('tag', '0002_alter_tagmodel_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='author',
            field=models.ManyToManyField(blank=True, to='authors.authormodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='Project_photos', to='photos.photomodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='stacks',
            field=models.ManyToManyField(blank=True, to='stack.stackmodel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tag.tagmodel'),
        ),
    ]
