# Generated by Django 5.2.7 on 2025-10-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_projectmodel_author_alter_projectmodel_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
