# Generated by Django 5.2.7 on 2025-10-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_projectmodel_started_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
