# Generated by Django 5.2.7 on 2025-10-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_projectmodel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
