# Generated by Django 5.2.7 on 2025-10-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_alter_projectmodel_ended_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='project_photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectmodel')),
            ],
        ),
    ]
