# Generated by Django 5.2.7 on 2025-10-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='tag_name',
            field=models.CharField(max_length=100),
        ),
    ]
